# Generated by Django 5.2.8 on 2025-11-27 08:50

import authsystem.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authsystem.managers.CustomUserManager()),
            ],
        ),
    ]
