# Generated by Django 5.2.8 on 2025-11-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
