# Generated by Django 5.2.8 on 2025-11-28 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'User Logout'), ('PAGE_VIEW', 'Page View'), ('ERROR', 'Error'), ('CUSTOM', 'Custom')], max_length=20)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra', models.TextField(blank=True, help_text='Optional JSON/text details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['event'], name='authsystem__event_4abdeb_idx'), models.Index(fields=['timestamp'], name='authsystem__timesta_718ecf_idx'), models.Index(fields=['user'], name='authsystem__user_id_804ab0_idx')],
            },
        ),
    ]
