# Generated by Django 5.2.8 on 2025-12-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0005_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='extra',
            field=models.TextField(blank=True),
        ),
    ]
