# Generated by Django 5.2.8 on 2025-12-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatintel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatip',
            old_name='added_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='threatip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='threatip',
            name='ip',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='threatip',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
